services:
  pgdatabase:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=online_purchase
    # volumes:
    #   - "/home/ubuntu/PostgreSQL-Data-Pipeline/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin_password
    ports:
      - "8080:80"