---
- name: setup docker and docker compose
  hosts: aws
  remote_user: ubuntu

  tasks:
  - name: update packages
    become: yes
    apt:
      update_cache: true

  - name: install docker
    become: yes
    shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" -y
      apt-cache policy docker-ce
      sudo apt install docker-ce -y
      sudo systemctl status docker > docker_status.log 2>&1

  - name: Install docker compose
    become: yes
    shell: |
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      docker-compose --version
      
  - name: checkout git
    become: yes
    shell: |
      git clone https://github.com/Adebisea/PostgreSQL-Data-Pipeline.git

  - name: start postgres and pgadmin services
    become: yes
    shell: |
      cd PostgreSQL-Data-Pipeline/pgsetup
      sudo docker-compose -f docker-compose.yml up -d
      sudo docker cp /home/ubuntu/PostgreSQL-Data-Pipeline/data/OnlineRetail.csv pgsetup_pgdatabase_1:/var/lib/postgresql/data
